name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: smallma876/ci-templates/.github/workflows/npm-build.yml@main
    with:
      node-version: '24'
  docker:
    needs: build
    if: github.event_name == 'push'
    uses: smallma876/ci-templates/.github/workflows/docker-build.yml@main
    with:
      image-name: 'smallma876/orchestrator'
